//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarterKitAspNetCoreWebApp.AppResources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarterKitAspNetCoreWebApp.AppResources.AppLanguage", typeof(AppLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        #region GeneralName

        public static string Dashboard
        {
            get
            {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        public static string General
        {
            get
            {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        public static string StarterKitAspNetCoreWebApp
        {
            get
            {
                return ResourceManager.GetString("StarterKitAspNetCoreWebApp", resourceCulture);
            }
        }
        public static string Home
        {
            get
            {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        public static string Id
        {
            get
            {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        public static string isActive
        {
            get
            {
                return ResourceManager.GetString("isActive", resourceCulture);
            }
        }
        public static string Language
        {
            get
            {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        public static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        public static string ShowSideMenu
        {
            get
            {
                return ResourceManager.GetString("ShowSideMenu", resourceCulture);
            }
        }
        public static string ShowTiles
        {
            get
            {
                return ResourceManager.GetString("ShowTiles", resourceCulture);
            }
        }
        public static string ShowTopMenu
        {
            get
            {
                return ResourceManager.GetString("ShowTopMenu", resourceCulture);
            }
        }
        public static string UserPreferences
        {
            get
            {
                return ResourceManager.GetString("UserPreferences", resourceCulture);
            }
        }
        public static string Welcome
        {
            get
            {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }


        public static string CreatedOn
        {
            get
            {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }


        public static string ModifiedOn
        {
            get
            {
                return ResourceManager.GetString("ModifiedOn", resourceCulture);
            }
        }

        public static string CreatedBy
        {
            get
            {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }

        public static string ModifiedBy
        {
            get
            {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }


        public static string IPAddress
        {
            get
            {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }

        #endregion GeneralName

        #region Tables

        #region Action

        public static string Actions
        {
            get
            {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }

        public static string ActionNameAr
        {
            get
            {
                return ResourceManager.GetString("ActionNameAr", resourceCulture);
            }
        }


        public static string ActionNameEn
        {
            get
            {
                return ResourceManager.GetString("ActionNameEn", resourceCulture);
            }
        }




        #endregion Action
        #region AccountClass

       

        public static string AccountClassNameEn
        {
            get
            {
                return ResourceManager.GetString("AccountClassNameEn", resourceCulture);
            }
        }


        public static string AccountClassNameAr
        {
            get
            {
                return ResourceManager.GetString("AccountClassNameAr", resourceCulture);
            }
        }

        public static string Pre_StartNum
        {
            get
            {
                return ResourceManager.GetString("Pre_StartNum", resourceCulture);
            }
        }

        public static string LF_NatureOfAccountID
        {
            get
            {
                return ResourceManager.GetString("LF_NatureOfAccountID", resourceCulture);
            }
        }


        #endregion AccountClass

        #endregion Tables








    }
}
