CREATE TABLE [dbo].[AspNetUsers] (
    [UserId]               NVARCHAR (128)  NOT NULL,
    [Id]                   INT             IDENTITY (1, 1) NOT NULL,
    [FirstName]            NVARCHAR (50)   NULL,
    [LastName]             NVARCHAR (50)   NULL,
    [UserPhoto]            VARBINARY (MAX) NULL,
    [IsEmployee]           BIT             NOT NULL,
    [OrganizationEmail]    NVARCHAR (128)  NULL,
    [EmployeeCode]         NVARCHAR (5)    NULL,
    [Email]                NVARCHAR (128)  NULL,
    [EmailConfirmed]       BIT             NOT NULL,
    [PasswordHash]         NVARCHAR (128)  NULL,
    [SecurityStamp]        NVARCHAR (128)  NULL,
    [PhoneNumber]          NVARCHAR (15)   NULL,
    [PhoneNumberConfirmed] BIT             NOT NULL,
    [TwoFactorEnabled]     BIT             NOT NULL,
    [LockoutEndDateUtc]    DATETIME2 (7)   NULL,
    [LockoutEnabled]       BIT             NOT NULL,
    [AccessFailedCount]    INT             NOT NULL,
    [UserName]             NVARCHAR (50)   NOT NULL,
    [CreatedBy]            NVARCHAR (100)  DEFAULT ('EF Migration') NULL,
    [CreatedOn]            DATETIME2 (7)   DEFAULT (getutcdate()) NULL,
    [ModifiedBy]           NVARCHAR (100)  DEFAULT ('EF Migration') NULL,
    [ModifiedOn]           DATETIME2 (7)   DEFAULT (getutcdate()) NULL,
    [IPAddress]            NVARCHAR (15)   DEFAULT ('::1') NULL,
    [isActive]             BIT             DEFAULT ((1)) NULL,
    CONSTRAINT [PK_AspNetUsers] PRIMARY KEY CLUSTERED ([UserId] ASC)
);

