using Microsoft.EntityFrameworkCore.Migrations;

namespace StarterKitAspNetCoreWebApp.Migrations
{
    public partial class _4_Seeding_LT_Regions : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"

Delete from [dbo].[LT_Region]
GO

SET IDENTITY_INSERT dbo.LT_Region ON
GO
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0001', 1, N'GOV-0001', N'NO NAME GIVEN TILL DATE', N'NO NAME GIVEN TILL DATE')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0002', 2, N'GOV-0001', N'AMWAJ', N'أمواج')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0003', 3, N'GOV-0001', N'BUSAITEEN', N'البسيتين')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0004', 4, N'GOV-0001', N'HIDD', N'الحد')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0005', 5, N'GOV-0001', N'AL DAIR', N'الدير')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0006', 6, N'GOV-0001', N'AL SAYA', N'الساية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0007', 7, N'GOV-0001', N'MUHARRAQ', N'المحرق')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0008', 8, N'GOV-0001', N'HALAT AL SLETAH', N'حالة السلطة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0009', 9, N'GOV-0001', N'HALAT AL NEAIM', N'حالة النعيم')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0010', 10, N'GOV-0001', N'SAMAHEEJ', N'سماهيج')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0011', 11, N'GOV-0001', N'ARAD', N'عراد')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0012', 12, N'GOV-0001', N'QALALI', N'قلالي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0013', 13, N'GOV-0001', N'HIDD', N'مدينة سلمان الصناعية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0014', 14, N'GOV-0002', N'ABU AL  AYASH', N'أبو العيش')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0015', 15, N'GOV-0002', N'ABU BHAM', N'أبو بهام')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0016', 16, N'GOV-0002', N'AL BURHAMA', N'البرهامة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0017', 17, N'GOV-0002', N'AL HAMRIYA', N'الحمرية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0018', 18, N'GOV-0002', N'AL KHARIJIYAH', N'الخارجية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0019', 19, N'GOV-0002', N'KHAMIS', N'الخميس')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0020', 20, N'GOV-0002', N'AL DAIH', N'الديه')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0021', 21, N'GOV-0002', N'ZINJ', N'الزنج')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0022', 22, N'GOV-0002', N'SOUTH SEHLA', N'السهلة الجنوبية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0023', 23, N'GOV-0002', N'AL SEEF', N'السيف')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0024', 24, N'GOV-0002', N'SALIHIYA', N'الصالحية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0025', 25, N'GOV-0002', N'AL AKR AL SHARQI', N'العكر الشرقي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0026', 26, N'GOV-0002', N'AL AKR AL GHARBI', N'العكر الغربي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0027', 27, N'GOV-0002', N'AL QARYAH', N'القرية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0028', 28, N'GOV-0002', N'AL QAL AH', N'القلعة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0029', 29, N'GOV-0002', N'AL MUSALLA', N'المصلى')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0030', 30, N'GOV-0002', N'AL MA AMEER', N'المعامير')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0031', 31, N'GOV-0002', N'MANAMA / UMM ALHASSAM', N'المنامة/أم الحصم')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0032', 32, N'GOV-0002', N'MANAMA / ALJUFFAIR', N'المنامة/الجفير')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0033', 33, N'GOV-0002', N'MANAMA / ALHOORA', N'المنامة/الحورة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0034', 34, N'GOV-0002', N'MANAMA / ALSUQAYYAH', N'المنامة/السقية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0035', 35, N'GOV-0002', N'MANAMA / ALSALMANIYA', N'المنامة/السلمانية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0036', 36, N'GOV-0002', N'MANAMA / ALSUWAYFIYAH', N'المنامة/السويفية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0037', 37, N'GOV-0002', N'MANAMA / ALADLIYAH', N'المنامة/العدلية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0038', 38, N'GOV-0002', N'MANAMA / ALGHURAYFAH', N'المنامة/الغريفة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0039', 39, N'GOV-0002', N'MANAMA / ALFATEH', N'المنامة/الفاتح')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0040', 40, N'GOV-0002', N'MANAMA / ALQUDAYBIYAH', N'المنامة/القضيبية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0041', 41, N'GOV-0002', N'MANAMA / ALGUFUL', N'المنامة/القفول')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0042', 42, N'GOV-0002', N'MANAMA / ALCORNICHE', N'المنامة/الكورنيش')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0043', 43, N'GOV-0002', N'MANAMA / ALMAHUZ', N'المنامة/الماحوز')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0044', 44, N'GOV-0002', N'MANAMA / ALNAI M', N'المنامة/النعيم')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0045', 45, N'GOV-0002', N'MANAMA / SEA FRONT', N'المنامة/الواجهة البحرية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0046', 46, N'GOV-0002', N'MANAMA / BUASHIRAH', N'المنامة/بوعشيرة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0047', 47, N'GOV-0002', N'MANAMA / BUGHAZAL', N'المنامة/بوغزال')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0048', 48, N'GOV-0002', N'MANAMA / BUGHAZAL', N'المنامة/سيف أم الحصم')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0049', 49, N'GOV-0002', N'MANAMA / MINA SALMAN INDUSTRIAL AREA', N'المنامة/منطقة ميناء سلمان الصناعية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0050', 50, N'GOV-0002', N'DIPLOMATIC AREA', N'المنطقة الدبلوماسية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0051', 51, N'GOV-0002', N'INDUSTRIAL AREA', N'المنطقة الصناعية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0052', 52, N'GOV-0002', N'AL NASFA', N'الناصفة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0053', 53, N'GOV-0002', N'NABIH SALEH', N'النبيه صالح')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0054', 54, N'GOV-0002', N'AL NUWAIDRAT', N'النويدرات')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0055', 55, N'GOV-0002', N'BILAD AL QADEEM', N'بلاد القديم')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0056', 56, N'GOV-0002', N'TUBLI', N'توبلي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0057', 57, N'GOV-0002', N'JIDD ALI', N'جد علي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0058', 58, N'GOV-0002', N'JIDHAFS', N'جدحفص')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0059', 59, N'GOV-0002', N'JERDABC', N'جرداب')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0060', 60, N'GOV-0002', N'SUFALA', N'سفالة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0061', 61, N'GOV-0002', N'SANABIS', N'سنابس')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0062', 62, N'GOV-0002', N'SANAD', N'سند')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0063', 63, N'GOV-0002', N'TASHAN', N'طشان')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0064', 64, N'GOV-0002', N'ADHARI', N'عذاري')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0065', 65, N'GOV-0002', N'ARAD', N'عراد')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0066', 66, N'GOV-0002', N'KARBABAD', N'كرباباد')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0067', 67, N'GOV-0002', N'ISA TOWN', N'مدينة عيسى')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0068', 68, N'GOV-0002', N'MURQOBAN', N'مرقوبان')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0069', 69, N'GOV-0002', N'MAHAZZAH', N'مهزة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0070', 70, N'GOV-0002', N'WADIYAN', N'واديان')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0071', 71, N'GOV-0002', N'MANAMA / ALNAI M', N'وسط المنامة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0072', 72, N'GOV-0002', N'MANAMA CENTER', N'وسط المنامة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0073', 73, N'GOV-0003', N'ABU SAYBA', N'أبو صيبع')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0074', 74, N'GOV-0003', N'UMM AL NA SAN', N'أم النعسان')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0075', 75, N'GOV-0003', N'BUDAIYA', N'البديع')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0076', 76, N'GOV-0003', N'AL JASRAH', N'الجسرة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0077', 77, N'GOV-0003', N'AL JANABIYAH', N'الجنبية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0078', 78, N'GOV-0003', N'AL HAJAR', N'الحجر')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0079', 79, N'GOV-0003', N'AL DIRAZ', N'الدراز')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0080', 80, N'GOV-0003', N'NORTH SEHLA', N'السهلة الشمالية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0081', 81, N'GOV-0003', N'SHAKHURAH', N'الشاخورة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0082', 82, N'GOV-0003', N'AL SAFRIYAH', N'الصافرية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0083', 83, N'GOV-0003', N'AL QADAM', N'القدم')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0084', 84, N'GOV-0003', N'AL QURAYYAH', N'القريّة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0085', 85, N'GOV-0003', N'AL LAWZI', N'اللوزي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0086', 86, N'GOV-0003', N'MALKIYA', N'المالكية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0087', 87, N'GOV-0003', N'MOHAMMADIYAH', N'المحمدية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0088', 88, N'GOV-0003', N'NORTHERN CITY', N'المدينة الشمالية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0089', 89, N'GOV-0003', N'AL MARKH', N'المرخ')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0090', 90, N'GOV-0003', N'AL MAQSHA', N'المقشع')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0091', 91, N'GOV-0003', N'AL HAMALAH', N'الهملة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0092', 92, N'GOV-0003', N'BAR BAR', N'باربار')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0093', 93, N'GOV-0003', N'SAR', N'باربار')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0094', 94, N'GOV-0003', N'BANI JAMRAH', N'بني جمرة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0095', 95, N'GOV-0003', N'BU QUWAH', N'بو قوة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0096', 96, N'GOV-0003', N'BURI', N'بوري')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0097', 97, N'GOV-0003', N'JEBLAT HIBSHI', N'جبلة حبشي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0098', 98, N'GOV-0003', N'JID AL HAJ', N'جد الحاج')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0099', 99, N'GOV-0003', N'JIDDAH', N'جدة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0100', 100, N'GOV-0003', N'KING FAHAD CAUSWAY', N'جسر الملك فهد')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0101', 101, N'GOV-0003', N'JANNUSAN', N'جنوسان')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0102', 102, N'GOV-0003', N'HILLAT ABDULSALEH', N'حلة عبدالصالح')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0103', 103, N'GOV-0003', N'DAR KULAIB', N'دار كليب')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0104', 104, N'GOV-0003', N'DAMISTAB', N'دمستان')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0105', 105, N'GOV-0003', N'SAR', N'سار')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0106', 106, N'GOV-0003', N'SALIMABADCCCCCCCCCCCCC', N'سلماباد')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0107', 107, N'GOV-0003', N'SHAHRAKKAN', N'شهركان')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0108', 108, N'GOV-0003', N'SADAD', N'صدد')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0109', 109, N'GOV-0003', N'A ALI', N'عالي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0110', 110, N'GOV-0003', N'KARRANAH', N'كرانة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0111', 111, N'GOV-0003', N'KARZAKKAN', N'كرزكان')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0112', 112, N'GOV-0003', N'C', N'مدينة حمد')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0113', 113, N'GOV-0003', N'MAQABAH', N'مقابة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0114', 114, N'GOV-0003', N'HAWRAT A ALI', N'هورة عالي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0115', 115, N'GOV-0004', N'UM AL BAIDH', N'أم البيض')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0116', 116, N'GOV-0004', N'CCCCCC', N'أم جدر')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0117', 117, N'GOV-0004', N'UMM JIDR AL SUMMAN', N'أم جدر الصمان')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0118', 118, N'GOV-0004', N'UMMHAZWARAH', N'أم حزورة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0119', 119, N'GOV-0004', N'AL JA SIRAH', N'الجسيرة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0120', 120, N'GOV-0004', N'AL DUR', N'الدور')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0121', 121, N'GOV-0004', N'RIFFA / ALBUHAIR', N'الرفاع/البحير')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0122', 122, N'GOV-0004', N'RIFFA / ALHAJIYAT', N'الرفاع/الحجيات')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0123', 123, N'GOV-0004', N'RIFFA / ALHUNAYNIYAH', N'الرفاع/الحنينية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0124', 124, N'GOV-0004', N'RIFFA / ALROWDHA', N'الرفاع/الروضة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0125', 125, N'GOV-0004', N'RIFFA / ALROWDHA', N'الرفاع/الشرقي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0126', 126, N'GOV-0004', N'RIFFA / ALSHARGI', N'الرفاع/الشرقي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0127', 127, N'GOV-0004', N'RIFFA / ALSHAMALI', N'الرفاع/الشمالي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0128', 128, N'GOV-0004', N'RIFFA / ALGHARBI', N'الرفاع/الغربي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0129', 129, N'GOV-0004', N'RIFFA / MO ASKAR', N'الرفاع/المعسكر')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0130', 130, N'GOV-0004', N'RIFFA / ALBUKOWARAH', N'الرفاع/بو كوارة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0131', 131, N'GOV-0004', N'RIFFA / JARYALSHAIKH', N'الرفاع/جري الشيخ')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0132', 132, N'GOV-0004', N'RIFFA / SWAYFRA', N'الرفاع/سويفرة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0133', 133, N'GOV-0004', N'RIFFA / WADI ALSAIL', N'الرفاع/وادي السيل')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0134', 134, N'GOV-0004', N'AL RIFFAH', N'الرفة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0135', 135, N'GOV-0004', N'AL RUMAMIN', N'الرمامين')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0136', 136, N'GOV-0004', N'AL RUMAYTHAH', N'الرميثة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0137', 137, N'GOV-0004', N'ZALLAQ', N'الزلاق')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0138', 138, N'GOV-0004', N'AL SHABAK', N'الشبك')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0139', 139, N'GOV-0004', N'AL SAKHIR', N'الصخير')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0140', 140, N'GOV-0004', N'AL AMUR', N'العمر')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0141', 141, N'GOV-0004', N'AL GHAYNAH', N'الغينة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0142', 142, N'GOV-0004', N'AL QURAYN', N'القرين')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0143', 143, N'GOV-0004', N'AL MAZROWIAH', N'المزروعية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0144', 144, N'GOV-0004', N'AL MA AMEER', N'المعامير')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0145', 145, N'GOV-0004', N'AL MAMTALAH', N'الممطلة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0146', 146, N'GOV-0004', N'AL NUWAIDRAT', N'النويدرات')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0147', 147, N'GOV-0004', N'JAZAER BEACH', N'بلاج الجزائر')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0148', 148, N'GOV-0004', N'JUZUR AL DAR', N'جزر الدار')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0149', 149, N'GOV-0004', N'JAZIRAT HAWAR', N'جزيرة حوار')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0150', 150, N'GOV-0004', N'JAU', N'جو')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0151', 151, N'GOV-0004', N'HIDD ALJAMAL', N'حد الجمل ')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0152', 152, N'GOV-0004', N'HAFIRAH', N'حفيرة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0153', 153, N'GOV-0004', N'DAR KULAIB', N'دار كليب')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0154', 154, N'GOV-0004', N'DURRAT AL BAHRAIN', N'درة البحرين ')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0155', 155, N'GOV-0004', N'RAS ABU JARJUR', N'رأس أبو جرجور')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0156', 156, N'GOV-0004', N'AL QARAH', N'رأس القارة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0157', 157, N'GOV-0004', N'RAS HAYYAN', N'رأس حيان')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0158', 158, N'GOV-0004', N'RAS ZUWAYED', N'رأس زويد')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0159', 159, N'GOV-0004', N'RUBUD AL GHARBIYAH', N'ربوب الغربية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0160', 160, N'GOV-0004', N'RUBUD AL SHARQIYAH', N'ربوب الغربية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0161', 161, N'GOV-0004', N'SAFREH', N'سافرة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0162', 162, N'GOV-0004', N'SUWAD AL JANUBIYAH', N'سوّاد الجنوبية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0163', 163, N'GOV-0004', N'SUWAD AL SHAMALIYAH', N'سوّاد الجنوبية')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0164', 164, N'GOV-0004', N'TARRAFI', N'طرافي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0165', 165, N'GOV-0004', N'A ALI', N'عالي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0166', 166, N'GOV-0004', N'AKSAR', N'عسكر')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0167', 167, N'GOV-0004', N'AWALIC', N'عوالي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0168', 168, N'GOV-0004', N'LHASSAY', N'لحسي')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0169', 169, N'GOV-0004', N'ZAYED TOWN', N'مدينة زايد')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0170', 170, N'GOV-0004', N'ISA TOWN', N'مدينة عيسى')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0171', 171, N'GOV-0004', N'MUZARRA', N'مزرع')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0172', 172, N'GOV-0004', N'MAMLAHAT AL MAMTALAH', N'مملحة الممطلة')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0173', 173, N'GOV-0004', N'HAWRAT SANAD', N'هورة سند')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0174', 174, N'GOV-0004', N'HAWRAT INGAH', N'هورة عنقه')
INSERT dbo.LT_Region(Region_Code, Id, LF_Governorate_Code, RegionEN, RegionAR) VALUES (N'REG-0175', 175, N'GOV-0004', N'WADI ALI', N'وادي علي')
GO
SET IDENTITY_INSERT dbo.LT_Region OFF
GO


             ");

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
