// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarterKitAspNetCoreWebApp.Presistance;

namespace StarterKitAspNetCoreWebApp.Migrations
{
    [DbContext(typeof(StarterKitProjectDBContext))]
    partial class StarterKitProjectDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.AspNetRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("IPAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("'::1'")
                        .HasMaxLength(15);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("RoleId");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.AspNetUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("IPAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("'::1'")
                        .HasMaxLength(15);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockoutEndDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("OrganizationEmail")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte[]>("UserPhoto")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("UserId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AspNetUserUserId")
                        .IsRequired()
                        .HasColumnName("UserId")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AspNetUserUserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AspNetUserUserId")
                        .HasColumnName("UserId")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("LoginProvider", "ProviderKey", "AspNetUserUserId");

                    b.HasIndex("AspNetUserUserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.AspNetUserRole", b =>
                {
                    b.Property<string>("AspNetUserUserId")
                        .HasColumnName("UserId")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("AspNetRoleRoleId")
                        .HasColumnName("RoleId")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("IPAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("'::1'")
                        .HasMaxLength(15);

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("AspNetUserUserId", "AspNetRoleRoleId");

                    b.HasIndex("AspNetRoleRoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.LT_Area", b =>
                {
                    b.Property<string>("Area_Code")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<int>("AreaNO")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("IPAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("'::1'")
                        .HasMaxLength(15);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LT_RegionRegion_Code")
                        .IsRequired()
                        .HasColumnName("LF_Region_Code")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("Area_Code");

                    b.HasIndex("LT_RegionRegion_Code");

                    b.ToTable("LT_Area");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.LT_Country", b =>
                {
                    b.Property<string>("Country_Code")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("Alpha2Code")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Alpha3Code")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Capital")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CountryNameAr")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CountryNameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("DialCode")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<int>("IACOCode")
                        .HasColumnType("int");

                    b.Property<string>("IPAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("'::1'")
                        .HasMaxLength(15);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsGCC")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("NationalityDescAr")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NationalityDescEn")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Region_Code")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("SubRegion")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SubRegion_Code")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("Country_Code");

                    b.ToTable("LT_Country");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.LT_DivisionType", b =>
                {
                    b.Property<string>("DivisionType_Code")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("DivisionNameAr")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DivisionNameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("IPAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("'::1'")
                        .HasMaxLength(15);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("DivisionType_Code");

                    b.ToTable("LT_DivisionType");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.LT_Governorate", b =>
                {
                    b.Property<string>("Governorate_Code")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("GovernorateAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GovernorateEN")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("IPAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("'::1'")
                        .HasMaxLength(15);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LT_CountryCountry_Code")
                        .IsRequired()
                        .HasColumnName("LF_Country_Code")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("Governorate_Code");

                    b.HasIndex("LT_CountryCountry_Code");

                    b.ToTable("LT_Governorate");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.LT_LookupTableReferance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("IPAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("'::1'")
                        .HasMaxLength(15);

                    b.Property<int?>("LastSerialNo")
                        .HasColumnType("int");

                    b.Property<string>("LookupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("LookupNameAr")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LookupNameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("PadLeftNo")
                        .HasColumnType("int");

                    b.Property<int?>("TemporarySerialNo")
                        .HasColumnType("int");

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id");

                    b.ToTable("LT_LookupTableReferance");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.LT_Region", b =>
                {
                    b.Property<string>("Region_Code")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("IPAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("'::1'")
                        .HasMaxLength(15);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LT_GovernorateGovernorate_Code")
                        .IsRequired()
                        .HasColumnName("LF_Governorate_Code")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("RegionAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("RegionEN")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("Region_Code");

                    b.HasIndex("LT_GovernorateGovernorate_Code");

                    b.ToTable("LT_Region");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.LT_Road", b =>
                {
                    b.Property<string>("Road_Code")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("IPAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("'::1'")
                        .HasMaxLength(15);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LT_AreaArea_Code")
                        .IsRequired()
                        .HasColumnName("LF_Area_Code")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("RoadNO")
                        .HasColumnType("int");

                    b.Property<string>("RoadNameAR")
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("RoadNameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("Road_Code");

                    b.HasIndex("LT_AreaArea_Code");

                    b.ToTable("LT_Road");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.SEC_RoleDelegation", b =>
                {
                    b.Property<string>("RoleDelegation_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AspNetRoleRoleId")
                        .HasColumnName("RoleId")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("AspNetUser1UserId")
                        .HasColumnName("LF_Destenation_UserId")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("AspNetUserUserId")
                        .IsRequired()
                        .HasColumnName("LF_Source_UserId")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("'::1'")
                        .HasMaxLength(15);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("RoleDelegation_Code");

                    b.HasIndex("AspNetRoleRoleId");

                    b.HasIndex("AspNetUser1UserId");

                    b.HasIndex("AspNetUserUserId");

                    b.ToTable("SEC_RoleDelegation");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.SEC_RolePermission", b =>
                {
                    b.Property<string>("RolePermission_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Action_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("AspNetRoleRoleId")
                        .IsRequired()
                        .HasColumnName("RoleId")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("IPAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("'::1'")
                        .HasMaxLength(15);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Module_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("RolePermission_Code");

                    b.HasIndex("AspNetRoleRoleId");

                    b.ToTable("SEC_RolePermission");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.SMT_Action", b =>
                {
                    b.Property<string>("Action_Code")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("ActionNameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ActionNameEn")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("IPAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("'::1'")
                        .HasMaxLength(15);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("Action_Code");

                    b.ToTable("SMT_Action");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.SMT_Module", b =>
                {
                    b.Property<string>("Module_Code")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("nvarchar(7)")
                        .HasMaxLength(7);

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("IPAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("'::1'")
                        .HasMaxLength(15);

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsMenu")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("ModuleActions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleNameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ModuleNameEn")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("OrderSequence")
                        .HasColumnType("int");

                    b.Property<string>("ParentModuleCode")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("RouteAction")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("RouteArea")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("RouteController")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("SystemTableName")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("TextColor")
                        .HasColumnType("nvarchar(7)")
                        .HasMaxLength(7);

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("Module_Code");

                    b.ToTable("SMT_Module");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.SMT_System", b =>
                {
                    b.Property<string>("System_Code")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("nvarchar(7)")
                        .HasMaxLength(7);

                    b.Property<byte[]>("BackgroundImageUrl")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("FontColor")
                        .HasColumnType("nvarchar(7)")
                        .HasMaxLength(7);

                    b.Property<string>("IPAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("'::1'")
                        .HasMaxLength(15);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("SystemAbbreviationAr")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("SystemAbbreviationEn")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("SystemNameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("SystemNameEn")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("System_Code");

                    b.ToTable("SMT_System");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.STR_Company", b =>
                {
                    b.Property<string>("Company_Code")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Area_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Building")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte[]>("CompanyLogo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CompanyNameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CompanyNameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("ContactFaxNo")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("ContactMobileNo")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ContactTelNo")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Country_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("FullAddress")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Governorate_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("'::1'")
                        .HasMaxLength(15);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("IsCostCentre")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOutLet")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsWareHouse")
                        .HasColumnType("bit");

                    b.Property<string>("LT_DivisionTypeDivisionType_Code")
                        .IsRequired()
                        .HasColumnName("LF_DivisionType_Code")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("'EF Migration'")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("POBox")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Region_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportFooter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Road_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vat_RegistrationNumber")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("WebSite")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("Company_Code");

                    b.HasIndex("LT_DivisionTypeDivisionType_Code");

                    b.ToTable("STR_Company");
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.AspNetUserClaim", b =>
                {
                    b.HasOne("StarterKitAspNetCoreWebApp.Models.AspNetUser", "AspNetUser")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("AspNetUserUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.AspNetUserLogin", b =>
                {
                    b.HasOne("StarterKitAspNetCoreWebApp.Models.AspNetUser", "AspNetUser")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("AspNetUserUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.AspNetUserRole", b =>
                {
                    b.HasOne("StarterKitAspNetCoreWebApp.Models.AspNetRole", "AspNetRole")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("AspNetRoleRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarterKitAspNetCoreWebApp.Models.AspNetUser", "AspNetUser")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("AspNetUserUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.LT_Area", b =>
                {
                    b.HasOne("StarterKitAspNetCoreWebApp.Models.LT_Region", "LT_Region")
                        .WithMany("LT_Area")
                        .HasForeignKey("LT_RegionRegion_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.LT_Governorate", b =>
                {
                    b.HasOne("StarterKitAspNetCoreWebApp.Models.LT_Country", "LT_Country")
                        .WithMany("LT_Governorate")
                        .HasForeignKey("LT_CountryCountry_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.LT_Region", b =>
                {
                    b.HasOne("StarterKitAspNetCoreWebApp.Models.LT_Governorate", "LT_Governorate")
                        .WithMany("LT_Region")
                        .HasForeignKey("LT_GovernorateGovernorate_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.LT_Road", b =>
                {
                    b.HasOne("StarterKitAspNetCoreWebApp.Models.LT_Area", "LT_Area")
                        .WithMany("LT_Road")
                        .HasForeignKey("LT_AreaArea_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.SEC_RoleDelegation", b =>
                {
                    b.HasOne("StarterKitAspNetCoreWebApp.Models.AspNetRole", "AspNetRole")
                        .WithMany("SEC_RoleDelegation")
                        .HasForeignKey("AspNetRoleRoleId");

                    b.HasOne("StarterKitAspNetCoreWebApp.Models.AspNetUser", "AspNetUser1")
                        .WithMany("SEC_RoleDelegationUserDestenation")
                        .HasForeignKey("AspNetUser1UserId");

                    b.HasOne("StarterKitAspNetCoreWebApp.Models.AspNetUser", "AspNetUser")
                        .WithMany("SEC_RoleDelegationUserSource")
                        .HasForeignKey("AspNetUserUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.SEC_RolePermission", b =>
                {
                    b.HasOne("StarterKitAspNetCoreWebApp.Models.AspNetRole", "AspNetRole")
                        .WithMany("SEC_RolePermission")
                        .HasForeignKey("AspNetRoleRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarterKitAspNetCoreWebApp.Models.STR_Company", b =>
                {
                    b.HasOne("StarterKitAspNetCoreWebApp.Models.LT_DivisionType", "LT_DivisionType")
                        .WithMany("STR_Company")
                        .HasForeignKey("LT_DivisionTypeDivisionType_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
